# This is a basic workflow that is manually triggered

name: hello world

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: push


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 hello-world-job:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "$(cat hello_world.txt)"
